x-gpu: &gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
services:
  e5-small: *gpu
  user-bge-m3: *gpu
  rapid-v5-mobile: *gpu
  whisper-large-v3: *gpu
